# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: Install Nuget

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
  displayName: Nuget stuff

- task: BatchScript@1
  inputs:
    filename: '$(Build.SourcesDirectory)\src\PokerLeagueManager.UI.Web\BuildAngular.bat'
  displayName: Build angular

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  displayName: Build VS

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  displayName: Run tests


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*dacpac'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
  displayName: Copy dacpacs

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/*.Commands.WebApi.zip
      **/*.Events.WebApi.zip
      **/*.Queries.WebApi.zip
      **/*.UI.Web.zip
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
  displayName: Copy zips
    
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\deploy'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\deploy' 
  displayName: Copy deploy

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src\PokerLeagueManager.Utilities\bin\$(buildConfiguration)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Utility'
  displayName: Copy Utility

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Provision Environment
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'DevOps CAT Workshops (e16d929e-2ebf-4445-805e-c032ef6c4559)'
    subscriptionName: 'e16d929e-2ebf-4445-805e-c032ef6c4559'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(adhocrg)'
    location: 'West US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)\deploy\Azure ARM\ArmTemplate.json'
    overrideParameters: '-appname $(adhocrg)'
    deploymentMode: 'Incremental'
  enabled: true

- task: AzureRmWebAppDeployment@4
  displayName: Deploy Commands Service
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'WorkshopAzure'
    appType: 'webApp'
    WebAppName: '$(adhocrg)-commands'
    packageForLinux: '$(Build.ArtifactStagingDirectory)\PokerLeagueManager.Commands.WebApi.zip'
  enabled: true

- task: AzureRmWebAppDeployment@4
  displayName: Deploy Events Service
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'WorkshopAzure'
    appType: 'webApp'
    WebAppName: '$(adhocrg)-events'
    packageForLinux: '$(Build.ArtifactStagingDirectory)\PokerLeagueManager.Events.WebApi.zip'
  enabled: true

- task: AzureRmWebAppDeployment@4
  displayName: Deploy Queries Service
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'WorkshopAzure'
    appType: 'webApp'
    WebAppName: '$(adhocrg)-queries'
    packageForLinux: '$(Build.ArtifactStagingDirectory)\PokerLeagueManager.Queries.WebApi.zip'
  enabled: true

- task: AzureRmWebAppDeployment@4
  displayName: Deploy UI Website
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'WorkshopAzure'
    appType: 'webApp'
    WebAppName: '$(adhocrg)'
    packageForLinux: '$(Build.ArtifactStagingDirectory)\PokerLeagueManager.UI.Web.zip'
  enabled: true

- task: SqlAzureDacpacDeployment@1
  displayName: Deploy Events DB
  inputs:
    azureSubscription: 'WorkshopAzure'
    AuthenticationType: 'server'
    ServerName: '$(adhocrg).database.windows.net'
    DatabaseName: 'Events'
    SqlUsername: 'dylan'
    SqlPassword: 'P2ssw0rd'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '$(Build.ArtifactStagingDirectory)\PokerLeagueManager.DB.EventStore.dacpac'
    IpDetectionMethod: 'AutoDetect'
    AdditionalArguments: '/p:CreateNewDatabase=true'
  enabled: true

- task: SqlAzureDacpacDeployment@1
  displayName: Deploy Queries DB
  inputs:
    azureSubscription: 'WorkshopAzure'
    AuthenticationType: 'server'
    ServerName: '$(adhocrg).database.windows.net'
    DatabaseName: 'Queries'
    SqlUsername: 'dylan'
    SqlPassword: 'P2ssw0rd'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '$(Build.ArtifactStagingDirectory)\PokerLeagueManager.DB.QueryStore.dacpac'
    IpDetectionMethod: 'AutoDetect'
    AdditionalArguments: '/p:CreateNewDatabase=true'
  enabled: true

- task: CmdLine@2
  displayName: Register Event Subscriber
  inputs:
    script: 'PokerLeagueManager.Utilities.exe CreateEventSubscriber $(adhocrg).database.windows.net Events dylan P2ssw0rd http://$(adhocrg)-events.azurewebsites.net'
    workingDirectory: '$(Build.ArtifactStagingDirectory)\Utility'
  enabled: true

- task: CmdLine@2
  displayName: Integration Test
  inputs:
    script: 'PokerLeagueManager.Utilities.exe GenerateSampleData http://$(adhocrg)-commands.azurewebsites.net 5'
    workingDirectory: '$(Build.ArtifactStagingDirectory)\Utility'
  enabled: true

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Delete Environment
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'DevOps CAT Workshops (e16d929e-2ebf-4445-805e-c032ef6c4559)'
    subscriptionName: 'e16d929e-2ebf-4445-805e-c032ef6c4559'
    action: 'DeleteRG'
    location: 'West US 2'
    resourceGroupName: '$(adhocrg)'
  enabled: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: Publish stuff
